-- Generated by matugen — do not edit manually
-- Loaded from wezterm.lua via dofile()
--
-- HYBRID STRATEGY:
--   • UI chrome (bg, fg, cursor, tab_bar, selection) follows the wallpaper.
--   • ANSI 1-6 / bright 9-14 are HARDCODED (Tokyo Night). Reason: Material You
--     derives all four accents (primary/secondary/tertiary/error) from a SINGLE
--     source color, so mapping them to ANSI red/green/yellow/blue/magenta/cyan
--     produces a monochrome palette on any non-rainbow wallpaper. Code syntax
--     highlighting needs six distinct hues; matugen can't deliver that.
--   • ANSI 8 (comment color) IS still wallpaper-driven via @outline — MD3
--     guarantees that token is WCAG-AA-compliant against surface backgrounds,
--     so comments stay readable but pick up a gentle wallpaper tint.

return {
  foreground = "#dfe2ef",
  background = "#0f131c",

  cursor_bg     = "#acc7ff",
  cursor_fg     = "#002f68",
  cursor_border = "#acc7ff",

  -- primary_container is the MD3-correct surface-tinted highlight (much
  -- subtler than primary, which would wash the whole selection in vivid pink).
  selection_bg = "#004492",
  selection_fg = "#d7e2ff",

  scrollbar_thumb = "#434751",
  split           = "#8d909c",

  ansi = {
    "#0f131c",   -- 0  black  (wallpaper-matched)
    "#f7768e",                          -- 1  red
    "#9ece6a",                          -- 2  green
    "#e0af68",                          -- 3  yellow
    "#7aa2f7",                          -- 4  blue
    "#bb9af7",                          -- 5  magenta
    "#7dcfff",                          -- 6  cyan
    "#dfe2ef", -- 7  white (wallpaper-matched)
  },
  brights = {
    "#8d909c",   -- 8  comments (wallpaper-tinted, AA-readable)
    "#ff7a93",                          -- 9  bright red
    "#b9f27c",                          -- 10 bright green
    "#ff9e64",                          -- 11 bright yellow / orange
    "#7da6ff",                          -- 12 bright blue
    "#c8a8ff",                          -- 13 bright magenta
    "#2ac3de",                          -- 14 bright cyan
    "#dfe2ef", -- 15 bright white (wallpaper-matched)
  },

  tab_bar = {
    background = "#0f131c",
    active_tab = {
      bg_color = "#acc7ff",
      fg_color = "#002f68",
    },
    inactive_tab = {
      bg_color = "#1b2029",
      fg_color = "#c3c6d3",
    },
    inactive_tab_hover = {
      bg_color = "#262a33",
      fg_color = "#dfe2ef",
    },
    new_tab = {
      bg_color = "#1b2029",
      fg_color = "#c3c6d3",
    },
    new_tab_hover = {
      bg_color = "#262a33",
      fg_color = "#dfe2ef",
    },
  },
}
